[workspace]
resolver = "2"
members = ["crates/protocol", "crates/master"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"
repository = "https://github.com/LeafdTK/MultiPaper"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1"
anyhow = "1"
dashmap = "6"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

multipaper-protocol = { path = "crates/protocol" }
